### ISSUE TITLE
Complete and rework the developer guide in the Readme

### ISSUE THREAD

**Issue by Askir** [HPI-SWA-Teaching/SWT16-Project-07#10]
### Story:
As a new Developer getting started
I want to see a guide instructing the use of this tool
In order to understand the basics of this tool and how it works

### Description:
Currently the guide is not very complete and doesn't actually work. The step definitions at the bottom are incomplete. Some setences have typos and bad wording.

### Acceptance Criteria:

- [ ] All stepdefinitions in the steps section so you can copy and paste
- [ ] Working acceptance test once you've completed all steps (They should not throw exceptions etc.)
- [ ] Better wording, no typos

**Comment by Askir** [comment]
8

**Comment by erksch** [comment]
The library methods should be in seperate blocks.

**Comment by Askir** [comment]
The fact that the libraries method needs to be class side should be fat!

**Comment by Askir** [comment]
no spaces in stepnames in readme so it doesn't crash.

**Comment by Askir** [comment]
assert should be change to self assert
