### ISSUE TITLE
Coveralls integration

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#14]
### Story

AS A Developer
I WANT TO see coveralls results 
IN ORDER TO verify my test coverage and be informed about the project state 

##### Why: (What value does it have? For whom?)
See 
##### What: (What should be implemented?)
Coveralls documentation can be found here: https://github.com/hpi-swa/smalltalkCI

**Comment by Askir** [comment]
5
