### ISSUE TITLE
Move generated code to AcceptItGenerated  package

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#15]
### Story

AS A Developer
I WANT  generated code for the project to be in an acceptItGenerated rather than just a generated
IN ORDER TO find my code intuitively

##### What: (What should be implemented?)
We dont want generated code to be commited. Therefore there should be no "-" in the package name
### Acceptance Criteria

Generated Code can be found in acceptItGenerated  package

**Comment by Askir** [comment]
1
