### ISSUE TITLE
Saving method fails

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#16]
### Expected Behavior
When adding a new user story scenario we should be able to save it.

### Actual Behavior
When adding new user story scenarios, saving them fails and they mysteriously are still somehow saved 
Sometimes the saving fails completely and instead of the saved scenario text only ``error`` is visible in the method text field

### Steps to reproduce error

Try to add a new user story scenarios

**Comment by Askir** [comment]
13 - Not really estimatable, we just don't know enough about the code yet.
