### ISSUE TITLE
Clicking description in test runner results in red error screen with a yellow cross.

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#17]
### Expected Behavior
Nothing should happen, or maybe the code for those steps should be browsable.

### Actual Behavior
Big red error rectangle appears when clicking on methods in testrunner

### Steps to reproduce error
Take any user story an click on the steps.

**Comment by Askir** [comment]
Actually quite easily fixed but difficult to test. 3-5
