### ISSUE TITLE
Whitespaces should be allowed in user story titles and not lead to an error message

### ISSUE THREAD

**Issue by Askir** [HPI-SWA-Teaching/SWT16-Project-07#34]
### Story

AS A Developer or Customer
I WANT TO Be able to use whitespaces in user story titles
IN ORDER TO Write Descriptive User Story Titles

______________________________________________________________

### Expected Behavior
When naming a User Story with whitespaces it should just save like it usually does.

### Actual Behavior
It creates a "method/user story" with the title `error`

### Steps to reproduce error
Create a user story in the created user story class and use whitespaces in the title.

### Estimations:
Jascha: Since this requires us to check into how the parser works I'd say at least a 5.

**Comment by erksch** [comment]
5

**Comment by MarcelSchmidberger** [comment]
Estimation: 8

**Comment by Xhenet** [comment]
8
