### ISSUE TITLE
Libraries should be able to be created by subclassing ACLibrary instead of having to call generatedLibrary:

### ISSUE THREAD

**Issue by Askir** [HPI-SWA-Teaching/SWT16-Project-07#36]
### Story

AS A Developer
I WANT TO be able to subclass ACLibrary
IN ORDER TO Include already written Libraries and make the process smoother in general

### Acceptance Criteria

- [ ] generateLibraray becomes deprecated and subclassing ACLibrary is the new official methods
- [ ] The Readme represents this change in the step by step
- [ ] AcceptitGenerated becomes deprecated aswell

### Estimation:
Jascha: This should maybe already be possible but it has to be tested to be official. I'd expect a 3 maybe a 5.

**Comment by erksch** [comment]
8

**Comment by MarcelSchmidberger** [comment]
5

**Comment by Xhenet** [comment]
5

**Comment by Askir** [comment]
This already works but needs some testing and cleanup in ACLibrary
