### ISSUE TITLE
Failing Assertions in steps should be debuggable

### ISSUE THREAD

**Issue by Askir** [HPI-SWA-Teaching/SWT16-Project-07#37]
### Expected Behavior
When I see that an assertion fails I should be able to open the debugger and see what exactly went wrong.

### Actual Behavior
When clicking debug the image throws tons of exceptions and locks. So only a user interupt makes you able to use it again (alt + .)

### Steps to reproduce error
Let any sort of assertion fail in a then step and then try to figure out why it happens.
I'm pretty sure any other errors are also pretty bad to deal with.

### Estimations:
Jascha: This debugging stuff occurs because the blocks are saved instead of actual method executions. Which makes it really difficult for the image to track down where the error occurs. Fixing this is gonna require a major refactor which we aren't ready to do yet imo (not enough tests written yet). So I'd estimate a 13.

**Comment by erksch** [comment]
13

**Comment by Xhenet** [comment]
13

**Comment by MarcelSchmidberger** [comment]
13
