### ISSUE TITLE
Step like: "(then) I expect A to be true" not correctly parsed

### ISSUE THREAD

**Issue by Askir** [HPI-SWA-Teaching/SWT16-Project-07#39]
### Story

AS A Developer or Customer
I WANT TO type my given and then statements like a human being
IN ORDER TO write useful user stories

______________________________________________________________

### Expected Behavior
I type a statement like: Then I expect A to be true and it should parse the "true" as boolean or at least as a String.

### Actual Behavior
just look at this???
![parserfucktab](https://user-images.githubusercontent.com/10251955/40016342-51a5805e-57b6-11e8-89a6-7c9a11b583ca.png)

### Steps to reproduce error
See image and readme

### Estimation:
Jascha: We will have to look into another parser here *shudders* might unravel even worse code we'll see. Definitely at least an 5 though.

**Comment by Askir** [comment]
Parse for then variables seems incredibly broken.

**Comment by erksch** [comment]
8

**Comment by MarcelSchmidberger** [comment]
8
