### ISSUE TITLE
Test basic functionality of AccpetIt using acceptance tests

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#70]
### Story

AS A developer
I WANT TO have acceptance tests for key acceptit functionalities
IN ORDER TO ensure the functionality of acceptit and get more familiar with the testing procedure

##### Why: (What value does it have? For whom?)
Tests ensure quality and prevent changes from breaking previously working features
##### What: (What should be implemented?)
The following acceptance tests should be implemented: 

###### Creating a user story

**Feature**: Creating a user story
   As a developer
   I want to be able to create a user story
   In order to document my requirements

**Scenario:** Class creation
   Given a user story text
   When I create a user story with this text
   Then a new user story class should be created

###### Adding scenarios

**Feature:** Add scenarios to user stories
   As a developer
   I want to be able to add scenarios to an existing user story
   In order to specify a test for the feature

**Scenario:**
   Given a user story
       And a scenario text
   When I add this scenario text as method to the user story
   Then the user story should have this text as scenario

###### Run Scenarios

**Feature:** run
   As a developer
   I want to run my scenarios with implemented steps
   In order to test my features

**Scenario:**
   Given a scenario with implemented steps
       And the steps are valid
   When I run the scenario
   Then the testrunner should have a green bar

##### Done: (How can it be demonstrated?)
Tests running green in the Testrunner

### Acceptance Criteria
All tests are done with correctly implemented steps and tests all green

**Comment by Askir** [comment]
Estimation: 8
