### ISSUE TITLE
More specific error priniting for syntax errors

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#71]
### Story

AS A developer writing acceptance tests
I WANT TO receive clear error messages when a User story could not be created due to a syntax error
IN ORDER TO find my mistakes fast and not get frustrated

### Description
Syntax errors in user stories e.g. due to typos lead to an undescriptive error print.

![image](https://user-images.githubusercontent.com/29160369/41206477-dd138290-6d04-11e8-94f9-eec67af8c4c4.png)

##### Why: (What value does it have? For whom?)
For someone just getting started with acceptance testing these errors can be very time-consuming.
##### What: (What should be implemented?)
Better exception texts printing eg. "syntax error in line 3"
##### Done: (How can it be demonstrated?)
Syntax errors can be deduced easily

**Comment by Askir** [comment]
Estimation: 5

**Comment by MarcelSchmidberger** [comment]
3
