### ISSUE TITLE
Wrong order of Userstory statements?

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#72]
Not sure whether this is as it should be? The necessary order of the statements in a user story differs from the format used elsewhere.

### Expected Behavior

Usually Userstories have a format like this:

As a developer
I want to be able to create a user story
In order to document my requirements

This user story would not compile with acceptit.

### Actual Behavior

To work the order has to change bringing the **in order to** statement in front.

In order to document requirements
As a developer
I want to be able to create a user story'

### Steps to reproduce error

ACUserStory createUserStory:
'AC Accpeptance Test User Story Creation
In order to document requirements
As a developer
I want to be able to create a user story'

withCategory: 'acceptit-Acceptance-Tests'

**Comment by Askir** [comment]
Yeh we should switch it around

**Comment by Askir** [comment]
Estimation: 3
