### ISSUE TITLE
Whitespaces should be allowed in a scenario titles and not lead to an error message

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#73]
### Expected Behavior

The Example given in the default scenario indicates that spacing in names of scenarios is allowed: "Name of scenario"
![image](https://user-images.githubusercontent.com/29160369/41206685-2eccbac2-6d08-11e8-99ee-99e466108c08.png)

### Actual Behavior
Saving a scenario with spaces in the title results in an incorrect saving of it

![image](https://user-images.githubusercontent.com/29160369/41206710-a106d8b6-6d08-11e8-8e9a-7aa1063e32e6.png)

![image](https://user-images.githubusercontent.com/29160369/41206701-7291561e-6d08-11e8-833f-986a49badcf4.png)

**Comment by Askir** [comment]
#34 is exactly this issue but thanks for the screenshots

**Comment by Askir** [comment]
Estimation: 5
