### ISSUE TITLE
Complete Acceptance Test in README

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#83]
### Story

AS A developer starting with acceptance tests
I WANT TO be provided with a comprehensive guide explaining all the functionalities
IN ORDER TO remove the barrier to entry and help starting with acceptit

##### Why: (What value does it have? For whom?)
for someone new to acceptit
##### What: (What should be implemented?)
Improve readme to contain a sensible example with all step implementation
Maybe test some existing class e.g. Number / String for functionality
Show all syntax including And, add explanations (maybe from presentation content)
##### Done: (How can it be demonstrated?)
README contains complete acceptance test with step implementations 

### Acceptance Criteria
Test is green

**Comment by Askir** [comment]
I don't think we need that once we have tested acceptIt with acceptIt do we? I feel like our own acceptance tests should be a good enough example but I guess it could be a somewhat nice addition. Just not high priority :P

**Comment by MarcelSchmidberger** [comment]
Estimation: 3
