### ISSUE TITLE
Tests seem to cause issue running

### ISSUE THREAD

**Issue by MarcelSchmidberger** [HPI-SWA-Teaching/SWT16-Project-07#90]
I ran all the tests with "Run Coverage" maybe thats the issue right?

### Expected Behavior

Testrunner should run tests without problem

### Actual Behavior

Testrunner froze the image
![image](https://user-images.githubusercontent.com/29160369/41796297-3406f2d4-7666-11e8-816a-547fe2fe6554.png)

### Steps to reproduce error

Try running Tests, only have sample size 1, so not to sure if squeak is the issue

**Comment by Askir** [comment]
I think select all might have selected more tests that those that were shown I mean the progressbar has 144 tests showing although you only have one scneario.

**Comment by MarcelSchmidberger** [comment]
seems to have been only a singular occurrence.
